spring:
  data:
    mongodb:
      uri: mongodb://root:password@mongo:27017/taskdb?authSource=admin
      database: taskdb
      auto-index-creation: true
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: kafka:9092

minio:
  endpoint: http://minio:9000
  access-key: minio
  secret-key: minio123
  bucket-name: taskflow-attachments


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: ${spring.application.name}:docker:${spring.application.instance_id:${random.value}}
    preferIpAddress: false
    hostname: task-service