server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092  # Изменено с 29092 на 9092
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/auth_db
    user: user
    password: password
    schemas: public
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/db/migration
    clean-disabled: true
    out-of-order: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
    preferIpAddress: true

jwt:
  cookie-secure: false  # false для локальной разработки без HTTPS